services:
  postgres_midas:
    networks:
      - midas_network
    image: postgres:15-alpine
    container_name: postgres_midas
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: midasdb
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: midas_backend
    ports:
      - "${SERVER_PORT}:8080"
    depends_on:
      - postgres_midas
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - midas_network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: midas_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_BASE_URL=https://midas-production.up.railway.app
    networks:
      - midas_network

volumes:
  postgres_data:

networks:
  midas_network:
    driver: bridge
